# Generated by Django 5.2.7 on 2025-11-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajadores',
        ),
    ]
