# Generated by Django 5.2.7 on 2025-10-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('asignatura', models.CharField(max_length=30)),
                ('nombre_de_estudiante', models.CharField(max_length=100)),
            ],
        ),
    ]
