# Generated by Django 5.2.7 on 2025-10-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_cliente_tienda_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tienda',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=100),
        ),
    ]
