# Generated by Django 5.2.7 on 2025-10-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_remove_producto_tienda_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
