# Generated by Django 5.2.7 on 2025-10-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0005_tienda_zona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Examenes',
        ),
    ]
