# Generated by Django 5.2.7 on 2025-11-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0006_delete_estudiante_delete_examenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
